#!/usr/bin/env bash
############
# Date="Sam 2015-02-07"
# Author="berq"
############

lock() {
    i3lock -c 000000
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        #lock && sudo /usr/sbin/pm-suspend
        lock && systemctl suspend
        ;;
    reboot)
        #sudo /sbin/reboot 
	systemctl reboot
        ;;
    shutdown)
        #sudo /sbin/poweroff 
	systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 0
